FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=ci_badge
ENV MYSQL_USER=sonu
ENV MYSQL_PASSWORD=90avq*9QD#0K

# Expose the MySQL port
EXPOSE 3306
